= Collection of Ansible Playbooks to Setup a CI/CD Environment

== Requirements

Some playbooks use roles from Ansible Galaxy.
Therefore, run following command to install all necessary roles from Ansible Galaxy before using the playbooks:
[source,bash]
----
ansible-galaxy install -r requirements.yml
----

The playbooks are tested with Ansible 2.4.2.0.

== How to setup inventories

Use the +test+ inventory file as template and fill the required group with your used IP Address or domain.
The groups relates to the applications.

== Settings for Playbooks

Some setting for Gitlab and Jenkins are outsourced in own variable files (+vars/*.yml+).

=== Gitlab specific Settings
Please check the link:https://github.com/geerlingguy/ansible-role-gitlab[documentation of the role 'geerlingguy.gitlab'].

=== Jenkins specific Settings
Following variable are available, along with default values:

[source,yaml]
----
jenkins_home: "/opt/jenkins"
jenkins_http_port: "8083"
----

== Testing
It exists  a +Vagrantfile+ for testing. This file defines in sum four test environments

[cols="h,d,d",options="header"]
|===
|
| Docker container
| Virtual Box VM

| CentOS 7
| centos-docker
| centos-vm

| Ubuntu 16.04 LTS
| ubuntu-docker
| ubuntu-vm

|===


=== Based on Docker Container
Start the container with

[source,bash]
----
vagrant up <os>-docker
----

=== Based on Virtual Box
Start and prepare the VM with

[source,bash]
----
vagrant up <os>-vm
./postInstall.sh

vagrant password is: vagrant
----



// TODO: java and docker as role because they are required by the main apps and will not be used standalone.
