= Collection of Ansible Playbooks to Setup a CI/CD Environment

== Requirements

Some playbooks use roles from Ansible Galaxy.
Therefore, run following command to install all necessary roles from Ansible Galaxy before using the playbooks:
[source,bash]
----
ansible-galaxy install -r requirements.yml
----

The playbooks are tested with Ansible 2.10.9.

Currently, the playbooks are tested on following systems:
- Ubuntu-based
// - centos-based

== How to setup inventories

Use the +test+ inventory file as template and fill the required group with your used IP Address or domain.
The groups relates to the applications.

== Settings for Playbooks

Some setting for Gitlab and Jenkins are outsourced in own variable files (+vars/*.yml+).

=== Gitlab specific Settings
Please check the link:https://github.com/geerlingguy/ansible-role-gitlab[documentation of the role 'geerlingguy.gitlab'].

=== Jenkins specific Settings
Following variable are available, along with default values:

[source,yaml]
----
jenkins_home: "/opt/jenkins"
jenkins_http_port: "8083"

jenkins_admin_password: admin123
jenkins_admin_username: admin

jenkins_proxy_server: ""
jenkins_proxy_port: ""
jenkins_proxy_username: ""
jenkins_proxy_password: ""
jenkins_proxy_no_proxy_host: ""

jenkins_plugins: []

jenkins_custom_init_scripts: # has no default value, but this variable is optional
----

== Testing
It exists  a +Vagrantfile+ for testing. This file defines in sum four test environments

[cols="h,d,d",options="header"]
|===
|
| Docker container
| Virtual Box VM

| CentOS 7
| centos-docker
| centos-vm

| Ubuntu 16.04 LTS
| ubuntu-docker
| ubuntu-vm

|====== Based on Virtual Box
Start the VM with

[source,bash]
----
vagrant up <os>-vm
----


=== Based on Docker Container
Start the container with

[source,bash]
----
vagrant up <os>-docker
----



// TODO: java and docker as role because they are required by the main apps and will not be used standalone.
