- hosts: jenkins_app
  become_method: sudo
  become: true
  vars_files:
    - vars/jenkins.yml

  tasks:
    - import_role:
        name: jenkins
    - import_role:
        name: git
    - import_role:
        name: vagrant
