- hosts: nexus_app
  become_method: sudo
  become: yes
  tasks:
    - name: Download Nexus Archive
      get_url:
         url: https://sonatype-download.global.ssl.fastly.net/nexus/3/nexus-3.7.1-02-unix.tar.gz
         dest: /tmp

    - name: Add group Nexus
      group:
        name: nexus
        state: present

    - name: Add user nexus
      user:
        name: nexus
        state: present
        group: nexus
        createhome: no
    # TODO create a backup if sonatype-workspace exists

    - name: Unarchive Nexus
      unarchive:
        src: /tmp/nexus-3.7.1-02-unix.tar.gz
        remote_src: yes
        dest: /opt
        creates: /opt/nexus-3.7.1-02

    - name: Add nexus as owner of nexus installation
      file:
        path: "{{ item }}"
        owner: nexus
        recurse: yes
      with_items:
        - /opt/nexus-3.7.1-02
        - /opt/sonatype-work


    - name: Set link to nexus
      file:
        src: /opt/nexus-3.7.1-02
        dest: /opt/nexus3
        state: link

    - name: install Nexus as service
      copy: src=files/nexus/nexus3.service dest=/etc/systemd/system/

    - name: Start Nexus
      service:
        name: nexus3
        state: started
        enabled: yes
