- name: Add an Apt signing key for Terraform
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Add Terraform repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main contrib"
    state: present
    filename: terraform

- name: installl Terraform
  ansible.builtin.apt:
    name: terraform
    update_cache: yes
