- name: Add ansible stable repository from PPA and install its signing key on Ubuntu target
  ansible.builtin.apt_repository:
    repo: ppa:ansible/ansible

- name: install ansible and pip
  ansible.builtin.apt:
    name:
      - ansible-base
      - python3-pip
    update_cache: yes

- name: install needed python lib for ansible
  ansible.builtin.pip:
    name: hcloud
